"""
Base Interface for Speaker Diarization
Defines the abstract contract for all diarization implementations:
- NeMoSortformerDiarizer (Production / GPU Path using NVIDIA NeMo)
- MockDiarizer (Mock implementation for testing/dev environments)
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field


@dataclass
class SpeakerSegment:
    speaker_id: str                   # Persistent speaker ID: "speaker_0", "speaker_1", "speaker_2", "speaker_3"
    start: float                      # Seconds from call start
    end: float                        # Seconds from call start
    confidence: float = 0.95
    raw_model_speaker: str = ""       # Model-level raw internal label e.g. "speaker_channel_0"
    raw_sortformer_speaker: str = ""  # Backward compatible alias for raw_model_speaker
    session_id: str = ""              # Diarization streaming session ID
    is_mock: bool = False             # Whether this segment was generated by MockDiarizer
    state_preserved: bool = True      # Whether streaming state was preserved
    acoustic_speaker_changed: bool = False # Whether physical speaker changed from immediately preceding segment
    audio_segment: str = ""           # Formatted MM:SS.SS-MM:SS.SS


@dataclass
class SpeakerTrack:
    speaker_id: str                   # Persistent ID (e.g. "speaker_0")
    raw_label: str                    # Raw model label
    first_seen: float
    last_seen: float
    turn_count: int = 0
    total_duration: float = 0.0


class SpeakerDiarizer(ABC):
    """
    Abstract Base Class for Speaker Diarizers.
    Physical speaker diarization is strictly decoupled from conversational roles (AGENT/BORROWER).
    """

    @abstractmethod
    def process_audio_chunk(
        self,
        audio_chunk: bytes,
        timestamp: float,
        duration: float,
        chunk_id: Optional[str] = None,
        voice_features: Optional[Dict[str, Any]] = None,
    ) -> List[SpeakerSegment]:
        """Process streaming 16kHz PCM audio chunk and return speaker segments."""
        pass

    @abstractmethod
    def process_utterance_event(
        self,
        text: str,
        start_time: float,
        end_time: float,
        chunk_id: Optional[str] = None,
        speaker_hint: Optional[str] = None,
        background_hint: bool = False,
        voice_features: Optional[Dict[str, Any]] = None,
        voice_name: Optional[str] = None
    ) -> List[SpeakerSegment]:
        """Process an utterance event in the continuous streaming session."""
        pass

    @abstractmethod
    def get_tracks_summary(self) -> Dict[str, Any]:
        """Return diagnostic summary of diarizer state, tracks, and metadata."""
        pass

    @abstractmethod
    def reset(self) -> None:
        """Reset internal streaming state for a new call."""
        pass
